### ISSUE TITLE
IoT support roadmap/timeline

### ISSUE THREAD

**Issue by ajres** [actor-framework/actor-framework#254]
I'm evaluating CAF as a cross platform framework, one of my key requirements is to be able to use the same core framework from desktop to IoT devices.

Are there any more details on what your IoT support goals are, i.e. will CAF require a linux level OS (e.g. RPi), or will it scale down to micro controllers (e.g arduino).

Can you share where IoT support sits on your roadmap/timeline.

Andy

**Comment by Neverlord** [comment]
We are currently porting CAF to [RIOT-OS](http://riot-os.org). @josephnoir and @BytesGalore are the experts on this and have a running setup for `libcaf_core`. The branch `topic/riot` contains the required patches.

The port was tested on some boards so far (@josephnoir will know the details on this), but it currently requires relatively powerful boards. I cannot give you a timeline for when the networking parts are up and running, since the network stack of RIOT-OS is currently under development. Also, we are exploring some ideas for minimizing CAF's RAM usage and binary size (e.g., a global mailbox with a minimal dispatcher instead of the multicore-friendly default approach).

Dominik

**Comment by josephnoir** [comment]
As Dominik mentioned, our goal is to support embedded devices as well. We are focusing to support [RIOT](https://github.com/RIOT-OS/RIOT) to ease development.

For now, `libcaf_core` works when using the `topic/riot`branch of CAF and the `topic/caf`branch of my [RIOT fork](https://github.com/josephnoir/RIOT). Since our framework requires a lot of memory at the moment, we are using the stm32f4discovery boards for testing (1MB ROM and 192KB RAM). Be aware that RIOT does not support Exception on this board at the moment.

Getting `libcaf_io` (or similar functionality) to run is next up on my agenda. The next steps include the following (more or less simplified) tasks:

- [x] get `libcaf_core` running
- [ ] implement a transactional interface for actor communication
- [ ] multiplexing with the new RIOT network stack
- [ ] implement the network stack for CAF (UDP, 6LoWPAN, CoAP)
- [ ] port everything to RIOT
- [ ] do lots of testing

The last time I checked, compiling and running CAF on the RPi worked without adjustments.

Raphael

**Comment by ajres** [comment]
@Neverlord , @josephnoir, thanks for the feedback.

I hadn't discovered riot.os, it looks like a great platform to build on.

If CAF/Riot can eventually run in 128K RAM, it looks like that would open up access to quite a few boards.

**Comment by josephnoir** [comment]
That would be great indeed. I created a [wiki page](https://github.com/actor-framework/actor-framework/wiki/CAF-on-RIOT) to track the progress.

**Comment by Neverlord** [comment]
I close this for now, but please get in touch if you have more questions or comments. :)
